# Include before ESP-IDF's project.cmake. Select components with
# HA_ESP_LIB_COMPONENTS, or leave it unset to make all five available.
set(_ha_esp_available credential_store wifi_manager mqtt_connection ha_discovery usb_provisioning)
if(DEFINED HA_ESP_LIB_COMPONENTS)
    set(_ha_esp_selected ${HA_ESP_LIB_COMPONENTS})
else()
    set(_ha_esp_selected ${_ha_esp_available})
endif()
foreach(_ha_esp_component IN LISTS _ha_esp_selected)
    if(NOT _ha_esp_component IN_LIST _ha_esp_available)
        message(FATAL_ERROR "Unknown home-assistant-esp-lib component: ${_ha_esp_component}")
    endif()
endforeach()
if("usb_provisioning" IN_LIST _ha_esp_selected)
    list(APPEND _ha_esp_selected wifi_manager mqtt_connection)
endif()
if("wifi_manager" IN_LIST _ha_esp_selected OR "mqtt_connection" IN_LIST _ha_esp_selected)
    list(APPEND _ha_esp_selected credential_store)
endif()
list(REMOVE_DUPLICATES _ha_esp_selected)
foreach(_ha_esp_component IN LISTS _ha_esp_selected)
    list(APPEND EXTRA_COMPONENT_DIRS "${CMAKE_CURRENT_LIST_DIR}/../components/${_ha_esp_component}")
endforeach()
unset(_ha_esp_available)
unset(_ha_esp_selected)
unset(_ha_esp_component)
